# Generated by Django 2.2.8 on 2020-05-07 11:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=str, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug name')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2, verbose_name='Priority')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Notification level',
                'verbose_name_plural': 'Notification levels',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default=str, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug name')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is active')),
                ('subject', ckeditor.fields.RichTextField(default=str, max_length=300, verbose_name='Subject')),
                ('short_message', ckeditor.fields.RichTextField(default=str, help_text='Use for Firebase/Runtime messages', max_length=500, verbose_name='Short message')),
                ('full_message', ckeditor.fields.RichTextField(blank=True, default=str, verbose_name='Full message')),
                ('template', models.CharField(blank=True, default=str, help_text='If defined use istead full_message', max_length=255, verbose_name='Template path')),
                ('level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notifications', to='core.NotificationLevel', verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Notification template',
                'verbose_name_plural': 'Notification templates',
            },
        ),
    ]
